<!-- 
	show customer informations like amount and all transactions for this customer
	
	Julius Wukoutz
	24.01.2014
 -->
<div class="row-fluid">
    <div class="span4">
        <br>
        <h3>Guthaben</h3>
        <br>

        <div class="row-fluid">
            <div class="span12">
                
                <div class="grid-head">
                    <i class="icon-tasks"></i> Aktuelles Guthaben
                    <span class="label label-success pull-right"><?= $this->amount . ' €'; ?></span>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<h3>Transaktionsübersicht</h3>
<div class="row-fluid">
    <div class="span9">
        
        <div class="grid-head">
            <i class="icon-tasks"></i> Transaktionen
            <span class="label label-important pull-right"><?= $this->counter ?></span>
        </div>
        <table class="table table-condensed table-bordered table-striped" id="transaction-table">
            <thead>
                <tr>
                    <th class="grid-caption">Info</th>
                </tr>
            </thead>
            <tbody>
                
                <?php
                 foreach ($this->transactions as $transaction) { ?>
                    
                    <tr class="user-row">
                        <td><?= $transaction->getInfo (); ?></td>
                    </tr>
                
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
