<!-- 
	show a list of devices it is possible to create, modify or delete one
	it is also possible to set a listfilter
	
	Julius Wukoutz
	24.01.2014
 -->
<div class="row-fluid">
    <div class="span2">
        <?php echo $this->partial('_partials/adminmenu.phtml', array('action' => $this->action, 'authRole' => $this->authRole, 'menuOptions' => $this->menuOptions)); ?>
    </div>
    <div class="span10">
        <h3>Endgeräte</h3>
        <br>
        <div class="row-fluid">
            <div class="input-prepend pull-left">
                <span class="add-on"><i class="icon-plus-sign"></i></span>
                <a id="device-add" href="#!" onclick="javascript:editModal(null, 'device');" class="btn">Neue Endgeräte anlegen</a>
            </div>
            
            <div class="control-group pull-right">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-eye-open"></i></span>
                    <input type="text" id="search_field" name="search_field" value="<?= $this->filter; ?>" placeholder="alle Endgeräte anzeigen" />
                    <a id="search_btn" href="#!" onclick="javascript:search('devices');" class="btn">Suchen</a>
                </div>
            </div>
        </div>
        
        <form id="action_frm" action="devices">
            <input type="hidden" id="filter" name="filter" value="" />
            <div class="row-fluid">
                <div class="span12">
                    
                    <div class="grid-head">
                        <i class="icon-tasks"></i> Endgeräte
                        <span class="label label-important pull-right"><?= $this->counter ?></span>
                    </div>
                    <table class="table table-condensed table-bordered table-striped" id="device-table">
                        <thead>
                            <tr>
                                <th width="37px" class="grid-caption"></th>
                                <th class="grid-caption">GeräteNr</th>
                                <th class="grid-caption">Typ</th>
                                <th class="grid-caption">Login</th>
                                <th class="grid-caption">Beschreibung</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <?php foreach ($this->devices as $device) { ?>
                            
                                <tr class="user-row">
                                    <td class="warning">
                                        <i view-name="device" data-id="<?= $device->getId (); ?>" title="Endgerät bearbeiten" class="icon-edit"></i>&nbsp;
                                        <i view-name="device" data-id="<?= $device->getId (); ?>" title="Endgerät deaktivieren" class="icon-ban-circle">
                                    </td>
                                    <td><?= $device->getDeviceNr (); ?></td>
                                    <td><?= $device->getType (); ?></td>
                                    <td><?= $device->getIdentity (); ?></td>
                                    <td><?= $device->getDescription (); ?></td>
                                </tr>
                            
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>