<!-- 
	show a list of events it is possible to create, modify or delete one
	it is also possible to set a listfilter
	
	Andreas Ressmann
	31.03.2014
 -->
<?php echo $this->partial('_partials/adminmenu.phtml', array('action' => $this->action,'menuOptions' => $this->menuOptions)); ?>
    
<div class="span9">
	<h3>Eventliste</h3>
	<br>
	<div class="row-fluid">
	    <div class="input-prepend pull-left">
	    	<span class="add-on"><i class="icon-plus-sign"></i></span>
	        	<a id="event-add" href="#!" onclick="javascript:editModal(null, 'event');" class="btn">Neuen Event anlegen</a>
		</div>
	            
	    <div class="control-group pull-right">
	    	<div class="input-prepend">
	        	<span class="add-on"><i class="icon-eye-open"></i></span>
	            <input type="text" id="search_field" name="search_field" value="<?= $this->filter; ?>" placeholder="alle Events anzeigen" />
	            <a id="search_btn" href="#!" onclick="javascript:search('event');" class="btn">Suchen</a>
	        </div>
	    </div>
	</div>
        
    <form id="action_frm" action="events">
    	<input type="hidden" id="filter" name="filter" value="" />
        <div class="row-fluid">
	        <div class="span12">
	                    
		        <div class="grid-head">
		        	<i class="icon-tasks"></i> Events
		            <span class="label label-important pull-right"><?= $this->counter ?></span>
		       	</div>
		        
		        <table class="table table-condensed table-bordered table-striped" id="event-table">
					<thead>
		            	<tr>
		                	<th width="37px" class="grid-caption"></th>
		                    <th class="grid-caption">Titel</th>
		                    <th class="grid-caption">Von</th>
		                    <th class="grid-caption">Bis</th>
		                   	<th class="grid-caption">Beschreibung</th>
						</tr>
		           	</thead>
		       		<tbody>
		       			<tr class="user-row">
                                    <td class="warning">
                                        <i view-name="device" data-id="1" title="Endgerät bearbeiten" class="icon-edit"></i>&nbsp;
                                        <i view-name="device" data-id="1" title="Endgerät deaktivieren" class="icon-ban-circle">
                                    </td>
                                    <td>Event 1</td>
                                    <td>01.04.2014</td>
                                    <td>18.04.2014</td>
                                    <td>Hier die Beschreibung zu Event 1</td>
                                </tr>
                         <tr class="user-row">
                                    <td class="warning">
                                        <i view-name="device" data-id="1" title="Endgerät bearbeiten" class="icon-edit"></i>&nbsp;
                                        <i view-name="device" data-id="1" title="Endgerät deaktivieren" class="icon-ban-circle">
                                    </td>
                                    <td>Event 2</td>
                                    <td>07.04.2014</td>
                                    <td>28.04.2014</td>
                                    <td>Hier die Beschreibung zu Event 2</td>
                                </tr>
                         <tr class="user-row">
                                    <td class="warning">
                                        <i view-name="device" data-id="1" title="Endgerät bearbeiten" class="icon-edit"></i>&nbsp;
                                        <i view-name="device" data-id="1" title="Endgerät deaktivieren" class="icon-ban-circle">
                                    </td>
                                    <td>Event 3</td>
                                    <td>01.05.2014</td>
                                    <td>12.05.2014</td>
                                    <td>Hier die Beschreibung zu Event 3</td>
                                </tr>
                       
				    </tbody>
				</table>
			</div>
		</div>
	</form>
</div>
