<!-- 
	show a list of events it is possible to create, modify or delete one
	it is also possible to set a listfilter
	
	Andreas Ressmann
	31.03.2014
 -->
 
<div class="row-fluid">
    
    <?php echo $this->partial('_partials/adminmenu.phtml', array('translator' => $this->translator, 'action' => $this->action,'menuOptions' => $this->menuOptions)); ?>
    
	<div class="span9">
		<h3><?= $this->translator->translate("view_showEvent"); ?></h3>
		<br>
	        
	    <form id="action_frm" action="event">
	    	<input type="hidden" id="filter" name="filter" value="" />
	        <div class="row-fluid">
		        <div class="span12">
		        
		        	<div class="row-fluid">
					    <div class="input-prepend pull-left">
					    	<span class="add-on"><i class="icon-plus-sign"></i></span>
					        	<a id="event-add" href="#!" onclick="javascript:editModal(null, 'event');" class="btn"><?= $this->translator->translate("view_newEvent"); ?></a>
						</div>
					            
					    <div class="control-group pull-right">
					    	<div class="input-prepend">
					        	<span class="add-on"><i class="icon-eye-open"></i></span>
					            <input type="text" id="search_field" name="search_field" value="<?= $this->filter; ?>" placeholder="<?= $this->translator->translate("view_showEvent"); ?>" />
					            <a id="search_btn" href="#!" onclick="javascript:search('event');" class="btn"><?= $this->translator->translate("event_search"); ?></a>
					        </div>
					    </div>
					</div>
		                    
			        <div class="grid-head">
			        	<i class="icon-tasks"></i> Events
			            <span class="label label-important pull-right"><?= $this->counter ?></span>
			       	</div>
			        
			        <table class="table table-condensed table-bordered table-striped" id="event-table">
						<thead>
			            	<tr>
			                	<th width="56px" class="grid-caption"></th>
			                    <th class="grid-caption"><?= $this->translator->translate("event_title"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("event_from"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("event_to"); ?></th>
			                   	<th class="grid-caption"><?= $this->translator->translate("event_description"); ?></th>
			                   	<th class="grid-caption"><?= $this->translator->translate("event_state"); ?></th>
			                   	<th class="grid-caption"><?= $this->translator->translate("tweet_entries"); ?></th>
							</tr>
			           	</thead>
			       		<tbody>
			       			<?php foreach ($this->events as $event) { ?>
	                            
	                                <tr class="user-row">
	                                    <td class="warning">
	                                        <i view-name="event" data-id="<?= $event->getId (); ?>" title="<?= $this->translator->translate("event_edit"); ?>" class="icon-edit"></i>
	                                        <i view-name="event" data-id="<?= $event->getId (); ?>" title="<?= $this->translator->translate("event_deactivate"); ?>" class="icon-ban-circle"></i>
	                                        <i view-name="event" data-id="<?= $event->getId (); ?>" title="<?= $this->translator->translate("event_clone"); ?>" class="icon-plus-sign"></i>
	                                    </td>
	                                    <td><?= $event->getEventTitle (); ?></td>
	                                    <td><?= date_format (new DateTime($event->getEventFrom ()), 'd.m.Y'); ?></td>
	                                    <td><?= date_format (new DateTime($event->getEventTo ()), 'd.m.Y'); ?></td>
	                                    <td><?= $event->getEventDescription (); ?></td>
	                                    <td><?php if($event->getEventState ()== '0') {echo $this->translator->translate("view_event_initalized");} elseif($event->getEventState ()== '1') {echo $this->translator->translate("view_event_collection");} else {echo $this->translator->translate("view_event_collected");} ?></td>
	                                    <td><?= $event->getEventTwCount (); ?></td>
	                                </tr>
	                            
	           				<?php } ?>
					    </tbody>
					</table>
					<?php echo $this->partial('_partials/pagination/pager.phtml', array('translator' => $this->translator, 'total' => $this->total, 'page' => $this->page)); ?>
				</div>
			</div>
		</form>
	</div>
</div>
