<!-- 
	show a list of sentiments it is possible to create, modify or delete one
	
	Moser Manfred
	14.05.2014
 -->
 
<div class="row-fluid">
    
    <?php echo $this->partial('_partials/adminmenu.phtml', array('action' => $this->action,'menuOptions' => $this->menuOptions)); ?>
    
	<div class="span9">
		<h3><?= $this->translator->translate("view_showSentiment"); ?></h3>
		<br>
	        
	    <form id="action_frm" action="sentiment">
	    	<input type="hidden" id="filter" name="filter" value="" />
	        <div class="row-fluid">
		        <div class="span12">
		        
		        	<div class="row-fluid">
					    <div class="input-prepend pull-left">
					    	<span class="add-on"><i class="icon-plus-sign"></i></span>
					        	<a id="sentiment-add" href="#!" onclick="javascript:editModal(null, 'sentiment');" class="btn"><?= $this->translator->translate("view_newSentiment"); ?></a>
						</div>
					            
					</div>
		                    
			        <div class="grid-head">
			        	<i class="icon-tasks"></i> Sentiments
			            <span class="label label-important pull-right"><?= $this->counter ?></span>
			       	</div>
			        
			        <table class="table table-condensed table-bordered table-striped" id="sentiment-table">
						<thead>
			            	<tr>
			                	<th width="37px" class="grid-caption"></th>
			                    <th class="grid-caption"><?= $this->translator->translate("sentiment_lang"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("sentiment_word"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("sentiment_weight"); ?></th>
							</tr>
			           	</thead>
			       		<tbody>
			       			<?php foreach ($this->sentiments as $sent) { ?>
	                            
	                                <tr class="user-row">
	                                    <td class="warning">
	                                        <i view-name="sentiment" data-id="<?= $sent->getId (); ?>" title="<?= $this->translator->translate("sentiment_edit"); ?>" class="icon-edit"></i>&nbsp;
	                                        <i view-name="sentiment" data-id="<?= $sent->getId (); ?>" title="<?= $this->translator->translate("sentiment_delete"); ?>" class="icon-ban-circle">
	                                    </td>
	                                    <td><?= $this->translator->translate($sent->getLangTxt()); ?></td>
	                                    <td><?= $sent->getSentimentWord(); ?></td>
	                                    <td><?= $sent->getSentimentWeight (); ?></td>
	                                </tr>
	           				<?php } ?>
					    </tbody>
					</table>
					<?php echo $this->partial('_partials/pagination/pager.phtml', array('total' => $this->total, 'page' => $this->page)); ?>
				</div>
			</div>
		</form>
	</div>
</div>