<!--
	show a list of tweets 

	Johannes Kammel
	28.9.2014
 -->
<?php echo $this->partial('_partials/tweets/scripts.phtml', array()); ?>

<div class="row-fluid">

    <?php echo $this->partial('_partials/adminmenu.phtml', array('translator' => $this->translator, 'action' => $this->action,'menuOptions' => $this->menuOptions)); ?>

	<div class="span9">
		<h3><?= $this->translator->translate("tweet_entries"); ?></h3>
		<br>
		
	    <form id="action_frm" action="tweets">
	    	<input type="hidden" id="filter" name="filter" value="" />
	        <div class="row-fluid">
		        <div class="span12">
		        	<div class="row-fluid">
		        	<table>
		        	<colgroup>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	</colgroup>
	        		<tr>
	        		<td>
		        		<i class="icon-tasks"></i> <?= $this->translator->translate("tweet_choose_event"); ?>
		        	</td>
		        	<td>
		        		<i class="icon-tasks"></i> Filter
		        	</td>
		        	<td></td>
		        	<td></td>		        	
		        	</tr>
		        	
		        	<tr>
		        	<td>
		        		<select name="choose_event" name="choose_event" id="choose_event" size="1">
				    		<option value="0"><?= $this->translator->translate("view_all"); ?></option>
				    		<?php foreach ($this->events as $event) { ?>
			                	<option <?= ($event->getId() == $this->selectedChooseEvent) ? 'selected' : ''; ?> value="<?= $event->getId (); ?>"><?= $event->getEventTitle (); ?></option>
			           		<?php } ?>
				    	</select>
				    	<input type="hidden" id="event_id" value="<?= $this->selectedChooseEvent; ?>" />
				    	<input type="hidden" id="tw_min" value="<?= $this->twMin['event_tw_count']; ?>" />
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		<span class="add-on"><i class="icon-briefcase" view-name="filter" data-id="<?= $this->selectedChooseFilter ?>" event-id="<?= $this->selectedChooseEvent; ?>" title="<?= $this->translator->translate("filter_edit"); ?>"></i>
		        		<i view-name="filter" data-id="<?= $this->selectedChooseFilter ?>" title="<?= $this->translator->translate("filter_delete"); ?>" class="icon-delete-filter"></i></span>
		        		<select name="choose_filter" name="choose_filter" id="choose_filter" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->filterObject as $curObj) { ?>
			                	<option <?= ($curObj->getId() == $this->selectedChooseFilter) ? 'selected' : ''; ?> value="<?= $curObj->getId (); ?>"><?= $curObj->getFilterName(); ?></option>
			           		<?php } ?>
				    	</select>
				    	
				    	<input type="hidden" id="filter_id" value="<?= ($this->selectedChooseEvent == '0') ? '0' : $this->selectedChooseFilter; ?>" />
				    	<a id="filter-add" href="#!" onclick="javascript:editModal(null, 'filter', <?= $this->selectedChooseEvent; ?> );" class="btn"><?=$this->translator->translate("view_newFilter");?></a>
				    	<a id="useFilter" href="#!" onclick="javascript:saveAnalysisSubmit();" class="btn"><?=$this->translator->translate("view_startAnalysis");?></a>
				    	</div>
		        	</td>
		        	<td>
		        	</td>
		        	<td>
				    	<div class="input-prepend">
				        	<span class="add-on"><i class="icon-eye-open"></i></span>
				            <input type="text" id="search_field" name="search_field" value="<?= $this->filter; ?>" placeholder="<?= $this->translator->translate("view_allTweets"); ?>" />
				            <a id="search_btn" href="#!" onclick="javascript:search('event');" class="btn"><?= $this->translator->translate("event_search"); ?></a>
				        </div>
		        	</td>
		        	</tr>
		        	
		        	</table>
					</div>
					
			        <div class="grid-head">
			        	<i class="icon-tasks"></i> Tweets
			            <span class="label label-important pull-right" id="counter"><?= $this->counter ?></span>
			       	</div>

			       	<input type="hidden" id="ignore_tweets" value=""/>
			        <table class="table table-condensed table-bordered table-striped" id="tweet-table">
						<thead>
			            	<tr>
			                	<th width="40px" class="grid-caption"><input type="checkbox" name="tweet_delete_all" onclick="javascript:select_all();" value=""></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tw_text"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tweet_date"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tw_user"); ?></th>
			                   	<th class="grid-caption"><?= $this->translator->translate("tw_location"); ?></th>
							</tr>
			           	</thead>
			       		<tbody>
			       			<?php foreach ($this->tweets as $tweet) { ?>

	                                <tr class="user-row">
	                                    <td class="warning">
	                                    <input type="checkbox" name="tweet_delete" title="delete" class="tweet_delete" value="<?= $tweet->getId (); ?>">
	                                    <button type="button" style='background-color: #FA5858;' class="btn btn-mini <?= in_array($tweet->getId(), $this->analysisIgnoreList) ? 'active' : ''; ?>" title="ignore" data-toggle="button" value="<?= $tweet->getId (); ?>">-</button>    
	                                    </td>
	                                    <td><?= $tweet->getTweetText (); ?></td>
	                                    <td><?= date_format (new DateTime($tweet->getCreationDate ()), 'd.m.Y'); ?></td>
	                                    <td><?= $tweet->getTweetUser (); ?></td>
	                                    <td><?= $tweet->getLocation (); ?></td>
	                                </tr>

	           				<?php } ?>
					    </tbody>
					</table>
					<a id="delete_tweets" href="#!" onclick="javascript:deleteTweets();" class="btn"><?=$this->translator->translate("view_deleteTweets");?></a><br /><br />
					<?php echo $this->partial('_partials/pagination/pager.phtml', array('translator' => $this->translator, 'total' => $this->total, 'page' => $this->page)); ?>
				</div>
			</div>
		</form>
	</div>
</div>