<!--
	show a list of tweets 

	Johannes Kammel
	28.9.2014
 -->

<?php echo $this->partial('_partials/tweets/scripts.phtml', array()); ?>

<div class="row-fluid">

    <?php echo $this->partial('_partials/adminmenu.phtml', array('action' => $this->action,'menuOptions' => $this->menuOptions)); ?>

	<div class="span9">
		<h3><?= $this->translator->translate("tweet_entries"); ?></h3>
		<br>
		
	    <form id="action_frm" action="tweets">
	    	<input type="hidden" id="filter" name="filter" value="" />
	        <div class="row-fluid">
		        <div class="span12">

		        	<div class="row-fluid">
			        	<i class="icon-tasks"></i> <?= $this->translator->translate("tweet_choose_event"); ?><br>
			        	<select name="choose_event" name="choose_event" id="choose_event" size="1">
				    		<option value="0"><?= $this->translator->translate("view_all"); ?></option>
				    		<?php foreach ($this->events as $event) { ?>
			                	<option <?= ($event->getId() == $this->selectedChooseEvent) ? 'selected' : ''; ?> value="<?= $event->getId (); ?>"><?= $event->getEventTitle (); ?></option>
			           		<?php } ?>
				    	</select>
		        	
					    <div class="control-group pull-right">
					    	<div class="input-prepend">
					        	<span class="add-on"><i class="icon-eye-open"></i></span>
					            <input type="text" id="search_field" name="search_field" value="<?= $this->filter; ?>" placeholder="<?= $this->translator->translate("view_allTweets"); ?>" />
					            <a id="search_btn" href="#!" onclick="javascript:search('event');" class="btn"><?= $this->translator->translate("event_search"); ?></a>
					        </div>
					    </div>
					</div>
		        
			        <div class="grid-head">
			        	<i class="icon-tasks"></i> Tweets
			            <span class="label label-important pull-right"><?= $this->counter ?></span>
			       	</div>

			        <table class="table table-condensed table-bordered table-striped" id="event-table">
						<thead>
			            	<tr>
			                	<th width="37px" class="grid-caption"></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tw_text"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tweet_date"); ?></th>
			                    <th class="grid-caption"><?= $this->translator->translate("tw_user"); ?></th>
			                   	<th class="grid-caption"><?= $this->translator->translate("tw_location"); ?></th>
							</tr>
			           	</thead>
			       		<tbody>
			       			<?php foreach ($this->tweets as $tweet) {
			       				?>

	                                <tr class="user-row">
	                                    <td class="warning">
	                                        
	                                    </td>
	                                    <td><?= $tweet->getTweetText (); ?></td>
	                                    <td><?= date_format (new DateTime($tweet->getCreationDate ()), 'd.m.Y'); ?></td>
	                                    <td><?= $tweet->getTweetUser (); ?></td>
	                                    <td><?= $tweet->getLocation (); ?></td>
	                                </tr>

	           				<?php } ?>
					    </tbody>
					</table>
				</div>
			</div>
		</form>
	</div>
</div>