<!-- 
	form to send a new password to the given indentity 
	second option is to display the change password fields 
	
	Julius Wukoutz
	24.01.2014
 -->
<?php if($this->mode == 'password-lost'): ?>
<div class="container">
	<div class="span3">&nbsp;</div>
	<div class="span4" style="width: 286px;">
	
		<form method="post" id="login_form" action="/auth/password" class="well" style="margin-bottom: 0; padding-bottom: 0;">
			<h3>Passwort vergessen</h3>
			<?php if($this->status == 'tokenSent'): ?>
			<?php echo '<h4>' . $this->statusText . '</h4>'; ?>
			<br>
			<a href="/auth/" class="btn" id="back">zur&uuml;ck</a>
			<br/>
			<?php else: ?>
			    
			    <?php echo '<h4 style="color:red">' . $this->statusText . '</h4>'; ?>
			<hr/>
			<fieldset>
				<div class="control-group">
					<div class="controls">
						<label for="username">Benutzername</label>
						<div class="input-prepend">
							<span class="add-on" rel="tooltip" title="E-Mail Adresse"><i class="icon-envelope"></i></span><input name="username" id="username" type="text" class="span3 required email" placeholder="" value="" />
						</div>
					</div>
				</div>
				
				<div class="clear"></div>
			
			
				<div class="form-actions" style="padding: 10px 0; margin: 10px 0">
					<button type="submit" class="btn <?php echo ($this->loginFailed ? 'btn-danger' : 'btn-primary'); ?>">Code anfordern</button>
					<a href="/auth/" class="btn" id="back">zur&uuml;ck</a>
				</div>
			</fieldset>
			<?php endif; ?>
		</form>

	</div>
</div>
<?php endif; ?>

<?php if($this->mode == 'password-reset'): ?>
<div class="container">
	<div class="span3">&nbsp;</div>
	<div class="span4" style="width: 286px;">
	
		<form method="post" id="login_form" action="/auth/password/token/<?php echo $this->token; ?>" class="well" style="margin-bottom: 0; padding-bottom: 0;">
			<h3>Passwort festlegen</h3>
			<h4><?php echo $this->statusText; ?></h4>
			<hr/>
			<fieldset>
			<?php if($this->status != 'tokenInvalid' && $this->status != 'success'): ?>
			
				<div class="control-group">
					<div class="controls">
						<label for="password">Passwort</label>
						<div class="input-prepend">
							<span class="add-on" rel="tooltip" title="Passwort"><i class="icon-lock"></i></span><input name="password" id="password" type="password" class="span3 required" />
						</div>		
					</div>
				</div>
				
				<div class="control-group">
					<div class="controls">
						<label for="password2">Passwort bestätigen</label>
						<div class="input-prepend">
							<span class="add-on" rel="tooltip" title="Passwort bestätigen"><i class="icon-lock"></i></span><input name="password2" id="password2" type="password" class="span3 required" />
						</div>		
					</div>
				</div>
				
				<div class="clear"></div>
			
			
				<div class="form-actions" style="padding: 10px 0; margin: 10px 0">
					<button type="submit" class="btn <?php echo ($this->loginFailed ? 'btn-danger' : 'btn-primary'); ?>">Passwort festlegen</button>
				</div>
			<?php else: ?>
				
				<?php if($this->status == 'tokenInvalid'): ?>
				<div class="control-group">
					<div class="controls">
						<a href="/auth/password" class="btn btn-primary">Code anfordern</a>		
					</div>
				</div>
				<?php else: ?>
				<div class="control-group">
					<div class="controls">
						<a href="/auth" class="btn btn-primary">Zum Login</a>		
					</div>
				</div>
				<?php endif; ?>
				
			<?php endif; ?>
			</fieldset>
		</form>

	</div>
</div>
<?php endif; ?>