<!DOCTYPE html>
<html lang="en">
	<meta charset="utf-8">
	<title>Tweet Statistics</title>
	
	<div id="tweet_statistics"></div>
    
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">
	google.load('visualization', '1.0', {'packages':['corechart']});
    
	google.setOnLoadCallback(drawVisualization);
      
	function drawVisualization() {

		var options = {'title':'Tweet Statistics',
		               'width':1200,
		               'height':500};
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Location');
		data.addColumn('number', 'Percent(%)');
		data.addRows([
		  ['Location1', 32.1],
		  ['Location2', 30.1],
		  ['Location3', 15.1],
		  ['Location4', 13.9],
		  ['Location5',  2.9],
		  ['Location6',  1.8],
		  ['Location7',  1.5],
		  ['Location8',  1.4],
		  ['Location9',  1.2]
		]);
	
		var chart = new google.visualization.PieChart(document.getElementById('tweet_statistics'));
		chart.draw(data, options);

	}
</script>