<!DOCTYPE html>
<html lang="en">
	<meta charset="utf-8">
	<title>Tweet Statistics</title>
	

<script type="text/javascript">

	$(document).ready(function() {

		$('#csvExport').hide();

		if ($('#analysis_id').val() != "") {
			$('#csvExport').show();
		}
		
		$('#choose_event').change(function() {
			$('#choose_filter').val(0);
			$('#choose_analysis').val(0);
			$('#action_frm').submit();		
		});
		$('#choose_filter').change(function(){
			$('#choose_analysis').val(0);
			$('#action_frm').submit();
		});
		$('#choose_analysis').change(function(){
			$('#action_frm').submit();
		});
		$('#csvExport').click(function() {
			$('#doExport').val(1);
			$('#action_frm').submit();
		});
	});
</script>
   
<form id="action_frm" action="statistics">
	<table>
		        	<colgroup>
		        	<col style="width:10%"/>
		        	<col style="width:10%"/>
		        	<col style="width:10%"/>
		        	<col style="width:60%"/>
		        	</colgroup>
	        		<tr>
	        		<td>
		        		<i class="icon-tasks"></i> <?= $this->translator->translate("tweet_choose_event"); ?>
		        	</td>
		        	<td>
		        		<i class="icon-tasks"></i> Filter
		        	</td>
		        	<td></td>
		        	<td></td>		        	
		        	</tr>
		        	
		        	<tr>
		        	<td>
		        		<select name="choose_event" name="choose_event" id="choose_event" size="1">
				    		<option value="0"><?= $this->translator->translate("view_all"); ?></option>
				    		<?php if($this->events[1]['id'] != null) foreach ($this->events as $event) { ?>
			                	<option <?= ($event['id'] == $this->selectedChooseEvent) ? 'selected' : ''; ?> value="<?= $event['id']; ?>"><?= $event['event_title']; ?></option>
			           		<?php } ?>
				    	</select>
				    	
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_filter" name="choose_filter" id="choose_filter" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->filter as $filter) { ?>
			                	<option <?= ($filter['id'] == $this->selectedChooseFilter) ? 'selected' : ''; ?> value="<?= $filter['id']; ?>"><?= $filter['filter_name']; ?></option>
			           		<?php } ?>
				    	</select>
				    	
				    	
				    	</div>
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_analysis" name="choose_analysis" id="choose_analysis" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->analysis as $analysis) { ?>
			                	<option <?= ($analysis->getId() == $this->selectedChooseAnalysis) ? 'selected' : ''; ?> value="<?= $analysis->getId(); ?>"><?= $analysis->getAnalysisDate(); ?></option>
			           		<?php } ?>
				    	</select>
				    	<input type="hidden" id="analysis_id" value="<?= $this->selectedChooseAnalysis; ?>"/>
				    	
				    	</div>
		        	</td>
		        	<td align="right">
		        		<a href="#" id="csvExport" name="csvExport"><img src="/assets/img/csv_file.png"></a>
		        		<input type="hidden" id="doExport" name="doExport" value=""/>
		        	</td>
		        	
		        	</tr>
		        	
		        	</table>
		        	
	
</form>
<h3><?= $this->translator->translate("tweet_statistics"); ?></h3>
	<table class="table table-bordered table-striped" width="400px">
		<thead>
			<tr>
				<th class="grid-caption"><?= $this->translator->translate("analysis_weight"); ?></th>
			    <th class="grid-caption"><?= $this->translator->translate("analysis_count"); ?></th>
			    <th class="grid-caption"><?= $this->translator->translate("analysis_percent"); ?></th>
			</tr>
		</thead>
		<tbody id="analysis_table">
			       			
		</tbody>
	</table>
	<div id="tweet_statistics" style="float:left;"></div>
	<div id="tweet_bar" style="float:left;"></div>
    
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">
	if($('#analysis_id').val() > 0){
	$.ajax({
			type: "POST",
		  	url: '../../../../api/getsentimentdata',
		  	data: { analyse_id: $('#analysis_id').val() }
		}).done(function(x){
			$('#analysis_table').html('<tr><td>Bewertung -5</td><td>'+x['minusfive']+'</td><td>'+x['minusfivepercent']+' %</td>'+
			'<tr><td>Bewertung -4</td><td>'+x['minusfour']+'</td><td>'+x['minusfourpercent']+' %</td>'+
			'<tr><td>Bewertung -3</td><td>'+x['minusthree']+'</td><td>'+x['minusthreepercent']+' %</td>'+
			'<tr><td>Bewertung -2</td><td>'+x['minustwo']+'</td><td>'+x['minustwopercent']+' %</td>'+
			'<tr><td>Bewertung -1</td><td>'+x['minusone']+'</td><td>'+x['minusonepercent']+' %</td>'+
			'<tr><td>Bewertung 0</td><td>'+x['zero']+'</td><td>'+x['zeropercent']+' %</td>'+
			'<tr><td>Bewertung 1</td><td>'+x['one']+'</td><td>'+x['onepercent']+' %</td>'+
			'<tr><td>Bewertung 2</td><td>'+x['two']+'</td><td>'+x['twopercent']+' %</td>'+
			'<tr><td>Bewertung 3</td><td>'+x['three']+'</td><td>'+x['threepercent']+' %</td>'+
			'<tr><td>Bewertung 4</td><td>'+x['four']+'</td><td>'+x['fourpercent']+' %</td>'+
			'<tr><td>Bewertung 5</td><td>'+x['five']+'</td><td>'+x['fivepercent']+' %</td>');
			
			var options = {
		               'width':700,
		               'height':500,
		               'colors': ['#632523','#953735','#D99694','#E6B9B8','#F2DCDB','#F2F2F2','#EBF1DE','#D7E4BD','#C3D69B','#77933C','#4F6228']};
								 
			data = new google.visualization.DataTable();
			data.addColumn('string', 'Valuation');
			data.addColumn('number', 'Percent(%)');
			
			data.addRows([
				  ['Bewertung -5', x['minusfive']],
				  ['Bewertung -4', x['minusfour']],
				  ['Bewertung -3', x['minusthree']],
				  ['Bewertung -2', x['minustwo']],
				  ['Bewertung -1', x['minusone']],
				  ['Bewertung 0', x['zero']],
				  ['Bewertung 1', x['one']],
				  ['Bewertung 2', x['two']],
				  ['Bewertung 3', x['three']],
				  ['Bewertung 4', x['four']],
				  ['Bewertung 5', x['five']]
				]);	
		
			var chart = new google.visualization.PieChart(document.getElementById('tweet_statistics'));
			chart.draw(data, options);
			
			var y = google.visualization.arrayToDataTable([
        	['Bewertung -5', 'Bewertung -4', 'Bewertung -3', 'Bewertung -2', 'Bewertung -1',
         	'Bewertung 0', 'Bewertung 1', 'Bewertung 2', 'Bewertung 3', 'Bewertung 4', 'Bewertung 5', { role: 'annotation' } ],
        	['', x['minusfivepercent'], x['minusfourpercent'], x['minusthreepercent'], x['minustwopercent'], x['minusonepercent'], x['zeropercent'], x['onepercent'], x['twopercent'], x['threepercent'], x['fourpercent'], x['fivepercent']],
      		]);
      		
      		 var options = {
       		 width: 600,
        	height: 400,
       	 	legend: { position: 'top', maxLines: 4 },
			bar: { groupWidth: '75%' },
        	isStacked: true,
      		'colors': ['#632523','#953735','#D99694','#E6B9B8','#F2DCDB','#F2F2F2','#EBF1DE','#D7E4BD','#C3D69B','#77933C','#4F6228']};
      		var chart = new google.visualization.BarChart((document.getElementById('tweet_bar')));
      		chart.draw(y, options);
		});
	}
	google.load('visualization', '1.0', {'packages':['corechart']});
	
	
</script>