<!DOCTYPE html>
<html lang="en">
	<meta charset="utf-8">
	<title>Tweet Statistics</title>
	

<script type="text/javascript">

	$(document).ready(function() {
		
		$('#choose_event').change(function() {
			$('#action_frm').submit();		
		});
		$('#choose_filter').change(function(){
			$('#action_frm').submit();
		});
		$('#choose_analysis').change(function(){
			$('#action_frm').submit();
		});
	});
</script>
   
<form id="action_frm" action="statistics">
	<table>
		        	<colgroup>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	</colgroup>
	        		<tr>
	        		<td>
		        		<i class="icon-tasks"></i> <?= $this->translator->translate("tweet_choose_event"); ?>
		        	</td>
		        	<td>
		        		<i class="icon-tasks"></i> Filter
		        	</td>
		        	<td></td>
		        	<td></td>		        	
		        	</tr>
		        	
		        	<tr>
		        	<td>
		        		<select name="choose_event" name="choose_event" id="choose_event" size="1">
				    		<option value="0"><?= $this->translator->translate("view_all"); ?></option>
				    		<?php if($this->events[1]['id'] != null) foreach ($this->events as $event) { ?>
			                	<option <?= ($event['id'] == $this->selectedChooseEvent) ? 'selected' : ''; ?> value="<?= $event['id']; ?>"><?= $event['event_title']; ?></option>
			           		<?php } ?>
				    	</select>
				    	
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_filter" name="choose_filter" id="choose_filter" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->filter as $filter) { ?>
			                	<option <?= ($filter['id'] == $this->selectedChooseFilter) ? 'selected' : ''; ?> value="<?= $filter['id']; ?>"><?= $filter['filter_name']; ?></option>
			           		<?php } ?>
				    	</select>
				    	
				    	
				    	</div>
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_analysis" name="choose_analysis" id="choose_analysis" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->analysis as $analysis) { ?>
			                	<option <?= ($analysis->getId() == $this->selectedChooseAnalysis) ? 'selected' : ''; ?> value="<?= $analysis->getId(); ?>"><?= $analysis->getAnalysisDate(); ?></option>
			           		<?php } ?>
				    	</select>
				    	<input type="hidden" id="analysis_id" value="<?= $this->selectedChooseAnalysis; ?>"/>
				    	
				    	</div>
		        	</td>
		        	
		        	</tr>
		        	
		        	</table>
</form>
	
	<div id="tweet_statistics"></div>
    
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">
	google.load('visualization', '1.0', {'packages':['corechart']});
    
	google.setOnLoadCallback(drawVisualization);
      
	function drawVisualization() {

		var options = {'title':'Tweet Statistics',
		               'width':1200,
		               'height':500};
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Location');
		data.addColumn('number', 'Percent(%)');

//		getting data
		get = [];
		$.ajax({
			type: "POST",
		  	url: '../../../../api/getsentimentdata',
		  	data: { analyse_id: $('#analysis_id').val() }
		}).done(function(data) {
				formData(data);	
			});
		function formData(weights){
			console.log(weights);
			
			get[0]=weights[0];
		}
		console.log(get);
		data.addRows([
		  ['Location1', get[0]],
		  ['Location2', 30.1],
		  ['Location3', 15.1],
		  ['Location4', 13.9],
		  ['Location5',  2.9],
		  ['Location6',  1.8],
		  ['Location8',  1.4],
		  ['Location9',  1.2]
		]);
	
		var chart = new google.visualization.PieChart(document.getElementById('tweet_statistics'));
		chart.draw(data, options);

	}
</script>