<!-- 
	header for the site 
	
	Julius Wukoutz
	24.01.2014
 -->
<div class="navbar navbar-fixed-top">
	<div id="header" class="navbar-inner">
		<div class="container-fluid">
			
			<a class="brand" href="/index">
				<img id="logo" title="Creditserver Logo" src="/assets/img/logo.png" alt="Creditserver Logo" />
			</a>
			
			<?php if($this->authRole != Core_Plugin_Acl::ROLE_GUEST): ?>
			<div class="btn-group pull-right" style="margin-right: -10px;">
				<div class="btn-group pull-left">
					<a class="btn"><i class="icon-user"></i> <?php echo $this->authName; ?></a>
					<a href="/auth/logout" class="btn btn-danger" style="height: 18px; padding: 6px 6px 2px 6px;"><i class="icon-off icon-white"></i></a>
				</div>
			</div>
			
			<!-- <div class="btn-group pull-right" style="margin-right: -10px;">
				<div class="btn-group pull-left" id="notifications">
					<a class="btn" href="#!" style="height: 18px; padding: 6px 6px 2px 6px;"><i class="icon fam-exclamation"></i></a>
					<a class="btn" id="notifications1" rel="popover">KW 45/2013 bestätigen</a>
				</div>
			</div> -->
			<?php endif; ?>
			
			<?php echo $this->partial('_partials/mainmenu.phtml'); ?>
			
		</div>
	</div>
</div>