<!-- 
	header for the site 
	
	Andreas Ressmann
	24.01.2014
 -->
<?php echo $this->partial('_partials/header/scripts.phtml'); ?>
 
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
        	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
            	<span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </a>
            <a class="brand" href="/index">
				<img id="logo" title="Twitteranalyser Logo" src="" alt="Twitteranalyser Logo" />
			</a>
            <div class="nav-collapse collapse">
				<p class="navbar-text pull-right">Sprache
					<select id="lang_selector" name="lang_selector" size="1">
						<option <?php echo ($this->lang == 'de') ? 'selected' : '' ?> value="de">Deutsch</option>
						<option <?php echo ($this->lang == 'en') ? 'selected' : '' ?> value="en">Englisch</option>
					</select>
				</p>
                    
				<?php echo $this->partial('_partials/mainmenu.phtml', array('controller' => $this->controller)); ?>
			</div>
		</div>
	</div>
</div>


