<!-- 
	header for the site 
	
	Andreas Ressmann
	24.01.2014
 -->
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
        	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
            	<span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </a>
            <a class="brand" href="/index">
				<img id="logo" title="Twitteranalyser Logo" src="/assets/img/logo.png" alt="Twitteranalyser Logo" />
			</a>
            <div class="nav-collapse collapse">
				<p class="navbar-text pull-right">Sprache
					<select name="multiling" size="1">
						<option>Deutsch</option>
						<option>Englisch</option>
					</select>
				</p>
                    
				<?php echo $this->partial('_partials/mainmenu.phtml'); ?>
			</div>
		</div>
	</div>
</div>


