<!-- 
	layout for the site 
	
	Andreas Ressmann
	31.03.2014
 -->

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Twitteranalyser</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headLink() ?>
		<?php echo $this->headScript() ?>
		
		<link rel="shortcut icon" href="/assets/img/fav.ico" type="image/x-icon" />
		
		<style type="text/css">
	        body {
	            padding-top: 60px;
	            padding-bottom: 40px;
	        }
	        .sidebar-nav {
	            padding: 9px 0;
	        }
	    </style>
	</head>
	<body>
		<div id="site">
			
			<?php echo $this->render('header.phtml'); ?>
			
			<div class="container-fluid" id="content_container" >
				<div class="row-fluid">
                	<?php echo $this->layout()->content ?>
                </div>
                
			</div>
			<hr>
			
			<?php echo $this->render('footer.phtml'); ?>
			
		</div>
		
		<!-- "Messenger": allows to use pnotify also server side -->
		<?php if($this->messenger === true): ?>
		<script type="text/javascript">
			$(document).ready(function() {
				$.pnotify({
				    title: '<?php echo $this->messenger_title; ?>',
				    text: '<?php echo $this->messenger_text; ?>',
				    type: '<?php echo $this->messenger_type; ?>',
				    animation: 'show'
				});
			});
			
		</script>
		<?php endif; ?>
		
		<div id="interface-lock" class="interface"></div>
		<div id="interface-lock-status" class="interface-inner rounded-xl" style="display:none">
		<img src="" style="margin-top: 5px" alt="Loading" /><br/><br/>DATEN WERDEN GELADEN
		</div>
		<div id="debug"></div>
		<div id="modal"></div>
	</body>
</html>