SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

DROP TABLE IF EXISTS `SENTIMENT`;
DROP TABLE IF EXISTS `FILT_COLUMN`;
DROP TABLE IF EXISTS `TWEET_FILTER`;
DROP TABLE IF EXISTS `TWEET_TAG`;
DROP TABLE IF EXISTS `TWEET_ENTRIES`;
DROP TABLE IF EXISTS `EVENT`;

# Event-Table where all events are saved
CREATE TABLE IF NOT EXISTS `EVENT` (
  `EVENT_ID` int(4) NOT NULL AUTO_INCREMENT,
  `EVENTNAME` varchar(100) NOT NULL,
  `EVENTDESCRIPTION` varchar(1000) NOT NULL,
  `STARTDATE` date DEFAULT NULL,
  `ENDDATE` date DEFAULT NULL,
  `TWEETCOUNT` int(6) DEFAULT NULL,
  `EVENTSTATE` char(1) DEFAULT '0', #0 Initial ; 1 Sammlung aktiv ; 2 Sammlung beendet
  PRIMARY KEY (`EVENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `EVENT` (`EVENT_ID`, `EVENTNAME`, `EVENTDESCRIPTION`, `STARTDATE`, `ENDDATE`, `TWEETCOUNT`) VALUES
(1, 'Spielberg 2014', 'Eine kurze Beschreibung zum Spielberg Event', '2014-05-24', '2014-07-01', 100);
INSERT INTO `EVENT` (`EVENT_ID`, `EVENTNAME`, `EVENTDESCRIPTION`, `STARTDATE`, `ENDDATE`, `TWEETCOUNT`) VALUES
(2, 'Theater Mamma Mia 2014', 'Eine kurze Beschreibung zum MAMA MIA Event', '2014-10-01', '2014-12-24', 100);

# Tweet Tags, which will be considered at collection time. These tags belongs to one event. At least one tag must exists for each event.
CREATE TABLE IF NOT EXISTS `TWEET_TAG` (
  `TAG_ID` int(4) NOT NULL AUTO_INCREMENT,
  `TAGNAME` varchar(50) NOT NULL,
  `EVENT_ID` int(4),
  PRIMARY KEY (`TAG_ID`),
  FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

INSERT INTO `TWEET_TAG` (`TAG_ID`, `TAGNAME`, `EVENT_ID`) VALUES (1, 'Spielberg', 1);
INSERT INTO `TWEET_TAG` (`TAG_ID`, `TAGNAME`, `EVENT_ID`) VALUES (2, 'F1', 1);
INSERT INTO `TWEET_TAG` (`TAG_ID`, `TAGNAME`, `EVENT_ID`) VALUES (3, 'Vettel', 1);
INSERT INTO `TWEET_TAG` (`TAG_ID`, `TAGNAME`, `EVENT_ID`) VALUES (4, 'Abba', 2);
INSERT INTO `TWEET_TAG` (`TAG_ID`, `TAGNAME`, `EVENT_ID`) VALUES (5, 'Mama Mia', 2);

# Tweet entries per Event
CREATE TABLE IF NOT EXISTS `TWEET_ENTRIES` (
  `TWEET_ID` int(8) NOT NULL AUTO_INCREMENT,
  `TWEETTEXT` varchar(4000) NOT NULL,
  `CREATIONDATE` date NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `LOCATION` varchar(100) DEFAULT NULL,
  `LANGUAGE` char(2) DEFAULT NULL,
  `DELETED` char(1) DEFAULT '0',
  `EVENT_ID` int(4),
  PRIMARY KEY (`TWEET_ID`),
  FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

INSERT INTO `TWEET_ENTRIES` (`TWEET_ID`, `TWEETTEXT`, `CREATIONDATE`, `USERNAME`, `LOCATION`, `LANGUAGE`, `EVENT_ID`) VALUES
(1, 'Well done - got the ticket for Spielberg GP 2014', '2014-05-05', 'Micael Steward', 'München', 'at', 1);
INSERT INTO `TWEET_ENTRIES` (`TWEET_ID`, `TWEETTEXT`, `CREATIONDATE`, `USERNAME`, `LOCATION`, `LANGUAGE`, `EVENT_ID`) VALUES
(2, 'I love Steven Spielberg', '2014-04-03', 'Doris Hart', 'Klagenfurt', 'at', 1);

CREATE TABLE IF NOT EXISTS `TWEET_FILTER` (
  `FILTER_ID` int(4) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(100) NOT NULL,
  `CONSIDER_TWEET` varchar(100) DEFAULT NULL,
  `IGNORE_TWEET` varchar(100) DEFAULT NULL,
  `TIME_START` date NOT NULL,
  `TIME_END` date NOT NULL,
  `EVENT_ID` int(4),
  PRIMARY KEY (`FILTER_ID`),
  FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

# All tweets in this table will be hide
CREATE TABLE IF NOT EXISTS `FILT_COLUMN` (
  `FILT_COL_ID` int(4) NOT NULL AUTO_INCREMENT,
  `FILTER_ID` int(4),
  `TWEET_ID` int(8),
  PRIMARY KEY (`FILT_COL_ID`),
  FOREIGN KEY (`FILTER_ID`) REFERENCES `TWEET_FILTER` (`FILTER_ID`),
  FOREIGN KEY (`TWEET_ID`) REFERENCES `TWEET_ENTRIES` (`TWEET_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4;

CREATE TABLE IF NOT EXISTS `SENTIMENT` (
  `SENT_ID` int(8) NOT NULL AUTO_INCREMENT,
  `SENT_TEXT` varchar(50) NOT NULL,
  `SENT_WEIGHT` int(1) NOT NULL,
  PRIMARY KEY (`SENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6;

