

<script type="text/javascript">

	$(document).ready(function() {
		
		$('#choose_event').change(function() {
			$('#choose_filter').val(0);
			$('#choose_analysis').val(0);
			$('#action_frm').submit();		
		});
		$('#choose_filter').change(function(){
			$('#choose_analysis').val(0);
			$('#action_frm').submit();
		});
		$('#choose_analysis').change(function(){
			$('#action_frm').submit();
		});
		
	});
</script>
   
<form id="action_frm" action="map">
	<table>
		        	<colgroup>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	<col style="width:30%"/>
		        	</colgroup>
	        		<tr>
	        		<td>
		        		<i class="icon-tasks"></i> <?= $this->translator->translate("tweet_choose_event"); ?>
		        	</td>
		        	<td>
		        		<i class="icon-tasks"></i> Filter
		        	</td>
		        	<td></td>
		        	<td></td>		        	
		        	</tr>
		        	
		        	<tr>
		        	<td>
		        		<select name="choose_event" name="choose_event" id="choose_event" size="1">
				    		<option value="0"><?= $this->translator->translate("view_all"); ?></option>
				    		<?php if($this->events[1]['id'] != null) foreach ($this->events as $event) { ?>
			                	<option <?= ($event['id'] == $this->selectedChooseEvent) ? 'selected' : ''; ?> value="<?= $event['id']; ?>"><?= $event['event_title']; ?></option>
			           		<?php } ?>
				    	</select>
				    	<input type="hidden" id="event_id" value="<?= $this->selectedChooseEvent; ?>"/>
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_filter" name="choose_filter" id="choose_filter" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->filter as $filter) { ?>
			                	<option <?= ($filter['id'] == $this->selectedChooseFilter) ? 'selected' : ''; ?> value="<?= $filter['id']; ?>"><?= $filter['filter_name']; ?></option>
			           		<?php } ?>
				    	</select>
				    	
				    	
				    	</div>
		        	</td>
		        	<td>
		        		<div class="input-prepend">
		        		
		        		<select name="choose_analysis" name="choose_analysis" id="choose_analysis" size="1">
		        			<option value="0"></option>
				    		<?php if($this->selectedChooseEvent)
				    				foreach ($this->analysis as $analysis) { ?>
			                	<option <?= ($analysis->getId() == $this->selectedChooseAnalysis) ? 'selected' : ''; ?> value="<?= $analysis->getId(); ?>"><?= $analysis->getAnalysisDate(); ?></option>
			           		<?php } ?>
				    	</select>
				    	<input type="hidden" id="analysis_id" value="<?= $this->selectedChooseAnalysis; ?>"/>
				    	
				    	</div>
		        	</td>
		        	
		        	</tr>
		        	
		        	</table>
		        	
	
</form>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<div style="width:100%;height:500px" id="gmeg_map_canvas"></div>

<script>

	var gmegMap, gmegMarker, gmegInfoWindow, gmegLatLng;

	function gmegInitializeMap(){
		gmegLatLng = new google.maps.LatLng(33.277148,8.05006);
		
		gmegMap = new google.maps.Map(document.getElementById("gmeg_map_canvas"),
					  { zoom:2,
			  			center:gmegLatLng,
			  			scrollwheel: false,
			  		    navigationControl: false,
			  		    mapTypeControl: false,
			  		    scaleControl: false,
			  		    draggable: false,
			  			mapTypeId:google.maps.MapTypeId.ROADMAP
			  		  });


//		var blueCircle = this.getCircle('blue');
//		var redCircle = this.getCircle('red');
//		var greenCircle = this.getCircle('green');

		$.ajax({
			type: "POST",
		  	url: '../../../../api/getmapdata',
		  	data: { analyse_id: $('#analysis_id').val(),
		  			event_id: $('#event_id').val() }
		}).done(function(data) {
			console.log(data);
//			var i = 0;
//			while (i < 20) {
//				var pos = new google.maps.LatLng(33.277148 + i, 8.05006);
//				
//				gmegMarker = new google.maps.Marker({
//					map: gmegMap,
//					position: pos,
//					icon: greenCircle
//				});
//
//				if (i%2 == 0) {
//					var pos = new google.maps.LatLng(33.277148 - i, 8.05006 - i);
//					
//					gmegMarker = new google.maps.Marker({
//						map: gmegMap,
//						position: pos,
//						icon: redCircle
//					});
//				}
//
//				if (i%2 == 1) {
//					var pos = new google.maps.LatLng(33.277148, 8.05006 - i);
//					
//					gmegMarker = new google.maps.Marker({
//						map: gmegMap,
//						position: pos,
//						icon: blueCircle
//					});
//				}
//
//				i++;
//			}
		});
	}

//	function getCircle (color) {
//		var circle ={
//			    path: google.maps.SymbolPath.CIRCLE,
//			    fillColor: color,
//			    fillOpacity: .6,
//			    scale: 5.5,
//			    strokeColor: 'white',
//			    strokeWeight: 1
//			};
//
//		return circle;
//	}
	
	google.maps.event.addDomListener(window, "load", gmegInitializeMap);

</script>