<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<div style="width:100%;height:500px" id="gmeg_map_canvas"></div>

<script>

	var gmegMap, gmegMarker, gmegInfoWindow, gmegLatLng;

	function gmegInitializeMap(){
		gmegLatLng = new google.maps.LatLng(33.277148,8.05006);
		
		gmegMap = new google.maps.Map(document.getElementById("gmeg_map_canvas"),
					  { zoom:2,
			  			center:gmegLatLng,
			  			scrollwheel: false,
			  		    navigationControl: false,
			  		    mapTypeControl: false,
			  		    scaleControl: false,
			  		    draggable: false,
			  			mapTypeId:google.maps.MapTypeId.ROADMAP
			  		  });

		//gmegMarker = new google.maps.Marker({map:gmegMap,position:gmegLatLng});
		//gmegInfoWindow = new google.maps.InfoWindow({content:'<b>ta</b><br><br>'});
		//gmegInfoWindow.open(gmegMap,gmegMarker);
	}

	google.maps.event.addDomListener(window, "load", gmegInitializeMap);

</script>